import RootLayout from "../app/layout";
import { AppProps } from "next/app";
import { Metadata } from "next";
import "../app/globals.css";
import { CategoriesProvider } from "@/app/contexts/CategoriesContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const MyApp: React.FC<AppProps> = ({ Component, pageProps }) => {
  return (
    <RootLayout>
      <CategoriesProvider>
        <Component {...pageProps} />
      </CategoriesProvider>
    </RootLayout>
  );
};

export default MyApp;
